import * as cheerio from "cheerio";
import type { EnforcementRecord, SourceDefinition } from "../types";
import { clean, reviewStatus, stableId } from "../normalize";

export const GENERIC_HTML_TABLE_VERSION="generic-html-table-v1.3.0";
function normalizeTime(value:string|null){if(!value)return {label:null,start:null,end:null};const values=[...value.matchAll(/(\d{1,2})時(?:(\d{1,2})分)?/g)].map(m=>`${m[1].padStart(2,"0")}:${(m[2]??"00").padStart(2,"0")}`);return {label:value,start:values[0]??null,end:values[1]??null};}
function pageYear(text:string){const reiwa=Number(text.match(/令和\s*(\d+)年/)?.[1]);return reiwa?2018+reiwa:new Date().getFullYear();}
function pageMonth(text:string){return Number(text.match(/(\d{1,2})月/)?.[1])||new Date().getMonth()+1;}
export function parseGenericHtmlTable(html:string,source:SourceDefinition):EnforcementRecord[]{
  const $=cheerio.load(html),body=clean($.root().text())??"",year=pageYear(body),defaultMonth=pageMonth(body),records:EnforcementRecord[]=[];
  $("table").each((_,table)=>{const rows=$(table).find("tr"),headers=rows.first().find("th,td").map((__,cell)=>clean($(cell).text())??"").get();const dateIndex=headers.findIndex(value=>/^(日|日付)$/.test(value)),timeIndex=headers.findIndex(value=>/時間/.test(value)),routeIndex=headers.findIndex(value=>/路線|道路/.test(value)),locationIndex=headers.findIndex(value=>/場所|地域|地区/.test(value)),categoryIndex=headers.findIndex(value=>/種別|重点|違反/.test(value));if(Math.min(dateIndex,timeIndex,routeIndex,locationIndex,categoryIndex)<0)return;let currentDate:string|null=null;rows.slice(1).each((__,tr)=>{const cells=$(tr).find("th,td").map((___,cell)=>clean($(cell).text())??"").get();if(cells.length<4)return;let offset=headers.length-cells.length;if(/^\d{1,2}$/.test(cells[0])){currentDate=`${year}-${String(defaultMonth).padStart(2,"0")}-${cells[0].padStart(2,"0")}`;offset=0;}const value=(index:number)=>cells[index-offset]??null,timeLabel=value(timeIndex),route=value(routeIndex),location=value(locationIndex),category=value(categoryIndex);if(!currentDate||!location||!category)return;const review=reviewStatus({date:currentDate,category});records.push({id:stableId([source.id,currentDate,timeLabel,location,route,category]),prefecture:source.prefecture,date:currentDate,timeLabel,startTime:null,endTime:null,location,route,category,policeStation:null,latitude:null,longitude:null,locationPrecision:/市内|区内|町内|村内|管内|全域|一円/.test(location)?"area_only":"approximate",sourceUrl:source.indexUrl,sourceTitle:source.title,...review,rawText:cells.join(" ")});});});
  if(records.length)return records;
  $("table tr").each((_,tr)=>{const cells=$(tr).find("th,td").map((__,cell)=>clean($(cell).text())).get().filter(Boolean) as string[];if(cells.length<4)return;
    const dateMatch=cells[0].match(/^(?:(\d{1,2})月)?(\d{1,2})(?:日)?/);if(!dateMatch)return;const month=Number(dateMatch[1])||defaultMonth,day=Number(dateMatch[2]),date=`${year}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`;
    const timeIndex=cells.findIndex(value=>/\d{1,2}時|午前|午後|夜間/.test(value)),time=normalizeTime(timeIndex>=0?cells[timeIndex]:null);const category=cells.find(value=>/取締|検問|速度|通行禁止|一時停止|信号|携帯|飲酒|シートベルト|交差点/.test(value))??null;
    const locationIndex=cells.findIndex((value,index)=>index>0&&/(市|区|町|村|郡).*(地内|付近|内)?$/.test(value));const rawLocation=locationIndex>=0?cells[locationIndex]:null,location=rawLocation&&/^(市内|区内|町内|村内|市街地)$/.test(rawLocation)&&locationIndex>0?`${cells[locationIndex-1]}${rawLocation}`:rawLocation;
    const route=cells.find(value=>/(国道|県道|市道|町道|村道|自動車道|線$|各路線|生活道路)/.test(value))??null,review=reviewStatus({date,category});records.push({id:stableId([source.id,date,time.label,location,route,category]),prefecture:source.prefecture,date,timeLabel:time.label,startTime:time.start,endTime:time.end,location,route,category,policeStation:null,latitude:null,longitude:null,locationPrecision:location?(/市内|区内|町内|村内|管内|市街地/.test(location)?"area_only":"approximate"):"unresolved",sourceUrl:source.indexUrl,sourceTitle:source.title,...review,rawText:cells.join(" ")});});return records;
}
