import * as cheerio from "cheerio";
import type{EnforcementRecord,SourceDefinition}from"../types";
import{stableId}from"../normalize";
import{parseCsv}from"./generic-csv";

export const OFFICIAL_HTML_STRUCTURES_VERSION="official-html-structures-v1.2.0";
const compact=(value:string)=>value.replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-0xFEE0)).replace(/[\s　]+/g," ").trim();
const iso=(year:number,month:number,day:number)=>`${year}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`;
const monthEnd=(year:number,month:number)=>iso(year,month,new Date(year,month,0).getDate());
const base=(source:SourceDefinition,url:string,fields:Partial<EnforcementRecord>&Pick<EnforcementRecord,"date"|"timeLabel"|"location"|"route"|"category"|"policeStation"|"locationPrecision"|"rawText">):EnforcementRecord=>({id:stableId([source.id,fields.date,fields.timeLabel,fields.location,fields.route,fields.category,fields.policeStation]),prefecture:source.prefecture,startTime:null,endTime:null,latitude:null,longitude:null,sourceUrl:url,sourceTitle:source.title,status:"confirmed",reviewReason:null,...fields});

export function parseMiyagiTimeGrid(html:string,source:SourceDefinition):EnforcementRecord[]{const $=cheerio.load(html),period=compact($("h2").filter((_,e)=>/令和.*～/.test($(e).text())).first().text()),m=period.match(/令和(\d+)年(\d+)月(\d+)日.*令和\d+年\d+月(\d+)日/);if(!m)return[];const year=2018+Number(m[1]),records:EnforcementRecord[]=[];$("table tr").slice(1).each((_,tr)=>{const cells=$(tr).find("th,td");if(cells.length!==5)return;const dm=compact(cells.eq(0).text()).match(/(\d+)月(\d+)日/);if(!dm)return;const date=iso(year,Number(dm[1]),Number(dm[2]));[2,3,4].forEach((cellIndex,index)=>{const timeLabel=["午前","午後","夜間"][index];cells.eq(cellIndex).find("h5").each((__,h)=>{const location=compact($(h).text());if(!location)return;records.push(base(source,source.indexUrl,{date,timeLabel,location,route:null,category:"交通指導取締り",policeStation:null,locationPrecision:"area_only",activeFrom:date,activeTo:date,rawText:`${date} ${timeLabel} ${location} 交通指導取締り`}));});});});return records;}

export function parseKanagawaMonthlyList(html:string,source:SourceDefinition):EnforcementRecord[]{const $=cheerio.load(html),updated=compact($(".main_large_updated").text()),ym=updated.match(/(\d{4})年(\d+)月/),heading=compact($("#sokudo").text()),mm=heading.match(/(\d+)月/);if(!ym||!mm)return[];const year=Number(ym[1]),month=Number(mm[1]),activeFrom=iso(year,month,1),activeTo=monthEnd(year,month),records:EnforcementRecord[]=[];let region="";$("#sokudo").nextUntil("h2").each((_,node)=>{if(node.tagName==="h3")region=compact($(node).text());if(node.tagName!=="ul"||!$(node).hasClass("list_01"))return;$(node).children("li").each((__,li)=>{const raw=compact($(li).text()),match=raw.match(/^(.*?)[（(]([^（）()]+)[）)]$/);if(!match)return;const route=match[1],place=match[2];let location=place;if(region==="横浜市"&&/^[^市]+区/.test(place))location=`横浜市${place}`;else if(region==="川崎市"&&/^[^市]+区/.test(place))location=`川崎市${place}`;else if(region==="相模原市"&&/^[^市]+区/.test(place))location=`相模原市${place}`;records.push(base(source,source.indexUrl,{date:null,timeLabel:"月間",location,route,category:"速度違反取締り",policeStation:null,locationPrecision:"area_only",activeFrom,activeTo,rawText:`${year}年${month}月 ${region} ${raw} 速度違反取締り`}));});});return records;}

export function parseTochigiHeadingSchedule(html:string,source:SourceDefinition):EnforcementRecord[]{const $=cheerio.load(html),updated=compact($("#tmp_update").text()),ym=updated.match(/(\d{4})年(\d+)月/);if(!ym)return[];const year=Number(ym[1]),records:EnforcementRecord[]=[];$("#tmp_contents h3").each((_,heading)=>{const label=compact($(heading).text()),dm=label.match(/(\d+)月(\d+)日/);if(!dm)return;const category=compact($(heading).next("p").text()).replace(/[「」]/g,"");if(!/(?:取締り|検問)/.test(category))return;const date=iso(year,Number(dm[1]),Number(dm[2])),timeLabel=label.replace(/^.*?日（.*?）/,"")||null;records.push(base(source,source.indexUrl,{date,timeLabel,location:"栃木県内全域",route:null,category,policeStation:null,locationPrecision:"area_only",activeFrom:date,activeTo:date,rawText:`${label} 県下一斉 ${category}`}));});return records;}

export function parseFukuokaStatewidePlan(html:string,source:SourceDefinition):EnforcementRecord[]{const $=cheerio.load(html),title=compact($("title").text()+" "+$("h1").first().text()+" "+$("body").text().slice(0,800)),ym=title.match(/(?:R|令和)\s*(\d+)[.年]\s*(\d+)月/);if(!ym)return[];const year=2018+Number(ym[1]),records:EnforcementRecord[]=[];$("table tr").slice(1).each((_,tr)=>{const cells=$(tr).find("th,td");if(cells.length<2)return;const dateText=compact(cells.eq(0).text()),category=compact(cells.eq(1).text());if(!/取締り/.test(category))return;const dm=dateText.match(/(\d+)月(\d+)日(?:\s*[～〜-]\s*(\d+)月(\d+)日)?/);if(!dm)return;const date=iso(year,Number(dm[1]),Number(dm[2])),activeTo=dm[3]?iso(year,Number(dm[3]),Number(dm[4])):date;records.push(base(source,source.indexUrl,{date,timeLabel:"県下一斉",location:"福岡県内全域",route:null,category,policeStation:null,locationPrecision:"area_only",activeFrom:date,activeTo,rawText:`${dateText} ${category} 福岡県内全域`}));});return records;}

export function parseNagasakiMonthlyPlan(html:string,source:SourceDefinition):EnforcementRecord[]{
  const $=cheerio.load(html),records:EnforcementRecord[]=[];
  $("h2").each((_,heading)=>{const hm=compact($(heading).text()).match(/令和(\d+)年(\d+)月/);if(!hm)return;const year=2018+Number(hm[1]),month=Number(hm[2]),table=$(heading).nextAll("table").first();if(!table.length)return;let day:number|null=null;
    table.find("tr").slice(1).each((__,tr)=>{const values=$(tr).find("th,td").map((___,cell)=>compact($(cell).text())).get();if(values.length<2)return;let timeIndex=0;if(/^\d{1,2}$/.test(values[0])){day=Number(values[0]);timeIndex=2;}if(day===null)return;const timeLabel=values[timeIndex];if(!/^(?:午前|午後|夜間)$/.test(timeLabel))return;const routeText=values.slice(timeIndex+1).join("/");if(!/^(?:\d{1,3})(?:\s*\/\s*\d{1,3})*$/.test(routeText))return;const date=iso(year,month,day);for(const number of routeText.split("/").map(value=>value.trim()).filter(Boolean)){const route=`国道${number}号`;records.push(base(source,source.indexUrl,{date,timeLabel,location:route,route,category:"交通指導取締り",policeStation:null,locationPrecision:"area_only",activeFrom:date,activeTo:date,rawText:`令和${hm[1]}年${month}月${day}日 ${timeLabel} ${route} 交通指導取締り`}));}});
  });return records;
}

export function parseTokyoPriorityCsv(text:string,source:SourceDefinition,csvUrl:string,activeFrom:string|null):EnforcementRecord[]{const rows=parseCsv(text);if(rows.length<2)return[];const headers=rows[0].map(compact),index=(name:string)=>headers.indexOf(name),records:EnforcementRecord[]=[];for(const row of rows.slice(1)){const ward=compact(row[index("行政区")]??""),station=compact(row[index("所属")]??""),location=compact(row[index("実施場所")]??""),route=compact(row[index("交差点・路線名")]??"");if(!ward||!station||!location||!route)continue;records.push(base(source,csvUrl,{date:null,timeLabel:null,location,route,category:"重点取締場所",policeStation:`${station}警察署`,locationPrecision:"area_only",activeFrom,activeTo:null,rawText:row.map(compact).join(" ")}));}return records;}
