"use client";
import { Circle, CircleMarker, MapContainer, Marker, Popup, TileLayer } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import L from "leaflet";
import type { Coordinates, NotificationRadius } from "@/lib/notification";
import type { EnforcementRecord } from "@/lib/types";
const icon=L.divIcon({className:"mapPin",html:"<span></span>",iconSize:[24,24],iconAnchor:[12,12]});
const notificationIcon=L.divIcon({className:"mapPin notificationPin",html:"<span></span>",iconSize:[30,30],iconAnchor:[15,15]});
const userIcon=L.divIcon({className:"userPin",html:"<span>●</span>",iconSize:[28,28],iconAnchor:[14,14]});
const formatUpdated=(value?:string)=>value?new Intl.DateTimeFormat("ja-JP",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"不明";
export default function MapView({records,notificationIds,areaAlertIds,currentLocation,radius}:{records:EnforcementRecord[];notificationIds:Set<string>;areaAlertIds:Set<string>;currentLocation:Coordinates|null;radius:NotificationRadius}){const points=records.filter(r=>r.latitude!==null&&r.longitude!==null);return <div className="mapWrap"><MapContainer center={[33.72,133.55]} zoom={8} className="map"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{currentLocation&&<><Circle center={[currentLocation.latitude,currentLocation.longitude]} radius={radius} pathOptions={{color:"#24725c",fillColor:"#4aa985",fillOpacity:.12}}/><Marker position={[currentLocation.latitude,currentLocation.longitude]} icon={userIcon}><Popup>シミュレーション現在地<br/>接近通知半径 {radius>=1000?`${radius/1000}km`:`${radius}m`}</Popup></Marker></>}{points.map(r=>{const candidate=notificationIds.has(r.id),areaCandidate=areaAlertIds.has(r.id);const popup=<Popup>{candidate&&<><b className="popupNotify">接近通知対象</b><br/></>}{areaCandidate&&<><b className="popupArea">エリア注意対象（地点ではありません）</b><br/></>}<b>{r.location}</b><br/>{r.category}<br/><small>{r.locationPrecision==="area_only"?"公開地域の代表表示。取締り地点ではありません。":r.locationPrecision}</small><br/><small>最終更新 {formatUpdated(r.updatedAt)}</small><br/><a href={r.sourceUrl} target="_blank">公式出典</a></Popup>;return r.locationPrecision==="area_only"?<CircleMarker key={r.id} center={[r.latitude!,r.longitude!]} radius={areaCandidate?10:5} pathOptions={{color:areaCandidate?"#b66b18":"#a69a87",fillColor:areaCandidate?"#e7a64c":"#c7bdaa",fillOpacity:areaCandidate?0.75:0.38,weight:areaCandidate?3:1}}>{popup}</CircleMarker>:<Marker key={r.id} position={[r.latitude!,r.longitude!]} icon={candidate?notificationIcon:icon}>{popup}</Marker>})}</MapContainer><div className="mapLegend"><span className="legendNotify"></span>接近通知 {notificationIds.size}件 <span className="legendArea"></span>エリア注意 {areaAlertIds.size}件<br/><small>丸印は公開地域の代表表示で、取締り地点ではありません。</small></div></div>}
