import type { SourceDefinition } from "./types";

export const sources: SourceDefinition[] = [
  { id: "ehime-public-enforcement", prefecture: "愛媛", title: "愛媛県警察 公開交通取締り", indexUrl: "https://www.police.pref.ehime.jp/kotsusidou/koukaitorishimari.htm", format: "pdf-index", adapter: "ehime-pdf-index" },
  { id: "kagawa-enforcement", prefecture: "香川", title: "香川県警察 交通指導取締り情報", indexUrl: "https://www.pref.kagawa.lg.jp/police/kotusido/koutsuu/sidou.html", format: "html", adapter: "kagawa-list" },
  { id: "kochi-priority-plan", prefecture: "高知", title: "高知県警察 重点交通取締計画", indexUrl: "https://www.police.pref.kochi.lg.jp/docs/2023103100093/", format: "pdf-index", adapter: "kochi-pdf" },
  { id: "tokushima-plan", prefecture: "徳島", title: "徳島県警察 交通取締計画", indexUrl: "https://www.police.pref.tokushima.jp/24kotuanzen/torimarinew/index.html", format: "html", adapter: "tokushima-table" },
  { id: "toyama-public-enforcement", prefecture: "富山", title: "富山県警察 公開交通指導取締り情報", indexUrl: "https://police.pref.toyama.jp/6116/anzen/koutsuuanzen/rule/kj00012592.html", format: "html", adapter: "generic-html-table" },
  { id: "shiga-public-enforcement", prefecture: "滋賀", title: "滋賀県警察 公開交通取締り", indexUrl: "https://www.pref.shiga.lg.jp/police/pa23/15821.html", format: "html", adapter: "generic-html-table" }
  ,{ id: "miyazaki-public-enforcement", prefecture: "宮崎", title: "宮崎県警察 交通指導取締り情報", indexUrl: "https://www.pref.miyazaki.lg.jp/police/kotsuanzen/torishimari/shido.html", format: "html", adapter: "generic-html-table" }
  ,{ id: "oita-public-enforcement", prefecture: "大分", title: "大分県警察 交通取締り情報", indexUrl: "https://www.pref.oita.jp/site/keisatu/torishimarijouhou2.html", format: "csv-index", adapter: "generic-csv-index" }
  ,{ id: "ibaraki-monthly-enforcement", prefecture: "茨城", title: "茨城県警察 交通安全指導・取締り情報", indexUrl: "https://www.pref.ibaraki.jp/kenkei/a02_traffic/torishimari/safety-instruction.html", format: "pdf-index", adapter: "monthly-pdf-index" }
  ,{ id: "aomori-priority-guidance", prefecture: "青森", title: "青森県警察 交通指導取締り重点路線・重点地区", indexUrl: "https://www.police.pref.aomori.jp/koutubu/sidou/torisimari_sisin.html", format: "pdf-index", adapter: "priority-guidance-pdf-index", pdfLinkIncludes: "/jyuuten/" }
  ,{ id: "osaka-speed-guidance", prefecture: "大阪", title: "大阪府警察 警察署別速度取締指針", indexUrl: "https://www.police.pref.osaka.lg.jp/kotsu/torishimari/6221.html", format: "pdf-index", adapter: "priority-guidance-pdf-index" }
  ,{ id: "hyogo-regional-enforcement", prefecture: "兵庫", title: "兵庫県警察 交通指導取締り計画", indexUrl: "https://www.police.pref.hyogo.lg.jp/traffic/violation/jyouho/index.htm", format: "pdf-index", adapter: "regional-schedule-pdf-index", regionLabels:["神戸","阪神","東播","西播","但馬","淡路","高速"] }
  ,{ id: "kumamoto-weekly-enforcement", prefecture: "熊本", title: "熊本県警察 交通取締情報", indexUrl: "https://www.pref.kumamoto.jp/site/police/list20-90.html", format: "html", adapter: "generic-html-linked-table", linkedHtmlLabelPattern:"交通取締" }
  ,{ id: "ishikawa-public-enforcement", prefecture: "石川", title: "石川県警察 公開交通指導取締り計画", indexUrl: "https://www2.police.pref.ishikawa.lg.jp/trafficsafety/trafficsafety04/", format: "pdf-index", adapter: "coordinate-triplet-pdf-index" }
  ,{ id: "tokyo-priority-enforcement", prefecture: "東京", title: "警視庁 重点取締場所", indexUrl: "https://www.keishicho.metro.tokyo.lg.jp/kotsu/torishimari/kokai_juten/jutentorishimari.html", format: "csv-index", adapter: "tokyo-priority-csv" }
  ,{ id: "kanagawa-monthly-speed", prefecture: "神奈川", title: "神奈川県警察 速度違反取締り実施場所", indexUrl: "https://www.police.pref.kanagawa.jp/kotsu/kotsu_torishimari/mesf2009.html", format: "html", adapter: "kanagawa-monthly-list" }
  ,{ id: "miyagi-enforcement-grid", prefecture: "宮城", title: "宮城県警察 交通指導取締り情報", indexUrl: "https://www.police.pref.miyagi.jp/sido/torisimari/sidouyotei.html", format: "html", adapter: "miyagi-time-grid" }
  ,{ id: "tochigi-monthly-enforcement", prefecture: "栃木", title: "栃木県警察 月間交通取締り情報", indexUrl: "https://www.pref.tochigi.lg.jp/keisatu/n28/torisimari/joho.html", format: "html", adapter: "tochigi-heading-schedule" }
  ,{ id: "chiba-public-enforcement", prefecture: "千葉", title: "千葉県警察 公開取締り", indexUrl: "https://www.police.pref.chiba.jp/kotsushidoka/traffic-safety_surveillanc.html", format: "pdf-index", adapter: "coordinate-schedule-pdf-index", coordinateScheduleLayout:"chiba_two_period", pdfLinkIncludes:"/content/common/" }
  ,{ id: "saitama-statewide-enforcement", prefecture: "埼玉", title: "埼玉県警察 県内全域取締日", indexUrl: "https://www.police.pref.saitama.lg.jp/f0020/kotsu/kenkaissei.html", format: "pdf-index", adapter: "coordinate-schedule-pdf-index", coordinateScheduleLayout:"saitama_statewide", pdfLinkIncludes:"/documents/12948/" }
  ,{ id: "fukui-public-enforcement", prefecture: "福井", title: "福井県警察 公開交通取締り情報", indexUrl: "https://www.pref.fukui.lg.jp/kenkei/doc/kenkei/koutsutorisimarijyoho.html", format: "pdf-index", adapter: "coordinate-grid-pdf-index", coordinateGridLayout:"fukui_daily_rows", pdfLinkIncludes:"koutsutorisimarijyoho_d/fil/" }
  ,{ id: "kagoshima-monthly-enforcement", prefecture: "鹿児島", title: "鹿児島県警察 交通取締り計画表", indexUrl: "https://www.pref.kagoshima.jp/ja22/koututorishimari.html", format: "pdf-index", adapter: "coordinate-grid-pdf-index", coordinateGridLayout:"kagoshima_area_matrix", pdfLinkIncludes:"/ja22/documents/" }
  ,{ id: "yamagata-monthly-enforcement", prefecture: "山形", title: "山形県警察 公開交通取締り", indexUrl: "https://www.pref.yamagata.jp/800030/kensei/police/koutsuuanzen/koukai.html", format: "pdf-index", adapter: "coordinate-grid-pdf-index", coordinateGridLayout:"yamagata_calendar_cells", pdfLinkIncludes:"/documents/5766/koukai" }
  ,{ id: "yamaguchi-speed-enforcement", prefecture: "山口", title: "山口県警察 速度取締り計画", indexUrl: "https://www.pref.yamaguchi.lg.jp/site/police/10456.html", format: "pdf-index", adapter: "coordinate-grid-pdf-index", coordinateGridLayout:"yamaguchi_route_time_matrix", pdfLinkIncludes:"/uploaded/attachment/" }
  ,{ id: "niigata-public-enforcement", prefecture: "新潟", title: "新潟県警察 公開交通取締り", indexUrl: "https://www.pref.niigata.lg.jp/site/kenkei/koutuusidou-torisimari.html", format: "pdf-index", adapter: "coordinate-grid-pdf-index", coordinateGridLayout:"niigata_two_column_daily", pdfLinkIncludes:"/uploaded/attachment/" }
  ,{ id: "fukuoka-statewide-enforcement", prefecture: "福岡", title: "福岡県警察 県下一斉取締り計画", indexUrl: "https://www.police.pref.fukuoka.jp/kotsu/koshi/moto/39th_motercycle_result.html", format: "html", adapter: "fukuoka-statewide-plan" }
  ,{ id: "wakayama-public-enforcement", prefecture: "和歌山", title: "和歌山県警察 公開交通取締情報", indexUrl: "https://www.police.pref.wakayama.lg.jp/02_koutsu/oshirase/koukaikoutsu/index.html", format: "pdf-index", adapter: "coordinate-grid-pdf-index", coordinateGridLayout:"wakayama_three_area_daily", pdfLinkIncludes:"/koukaikoutsu/documents/" }
  ,{ id: "saga-speed-enforcement", prefecture: "佐賀", title: "佐賀県警察 速度取締り装置による速度取締り計画", indexUrl: "https://www.police.pref.saga.jp/koutsu/kotsuihan/torisimari.html", format: "pdf-index", adapter: "coordinate-grid-pdf-index", coordinateGridLayout:"saga_station_symbol_matrix", pdfLinkIncludes:"/var/rev0/" }
  ,{ id: "iwate-daily-enforcement", prefecture: "岩手", title: "岩手県警察 交通取締り情報", indexUrl: "https://www.pref.iwate.jp/kenkei/kotsu/anzen/3000501.html", format: "pdf-index", adapter: "coordinate-grid-pdf-index", coordinateGridLayout:"iwate_daily_cards", pdfLinkIncludes:"/_page_/003/000/501/t" }
  ,{ id: "akita-monthly-enforcement", prefecture: "秋田", title: "秋田県警察 交通取締り実施予定", indexUrl: "https://www.police.pref.akita.lg.jp/kenkei/osirase", format: "pdf-index", adapter: "coordinate-grid-pdf-index", coordinateGridLayout:"akita_three_period_daily", linkedHtmlLabelPattern:"交通取締り実施予定", pdfLinkIncludes:"/uploads/contents/" }
  ,{ id: "nagasaki-monthly-enforcement", prefecture: "長崎", title: "長崎県警察 交通取締計画", indexUrl: "https://www.police.pref.nagasaki.jp/police/kotsu-anzen/kotsu-torishimari/kotsu-torishimari-joho/", format: "html", adapter: "nagasaki-monthly-plan" }
];
